name: Azure Terraform Deployment

on:
  workflow_call:
    inputs:
      project_id:
        required: true
        type: string
      region:
        required: true
        type: string
      cluster_name:
        required: true
        type: string
      database_name:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      DB_ADMIN_PASSWORD:
        required: true
      SLACK_WEBHOOK:
        required: false

jobs:
  terraform-azure:
    name: Terraform Azure Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Download tfvars
        uses: actions/download-artifact@v4
        with:
          name: terraform-vars
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ inputs.project_id }}
      
      - name: Terraform Init
        run: terraform init -input=false
      
      - name: Terraform Validate
        run: terraform validate
      
      - name: Terraform Plan
        run: terraform plan -input=false -var-file=terraform.tfvars
      
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false -var-file=terraform.tfvars
